title: "Memoria Astra"
description: "A Song Woven Across the Stars"
url: "https://memoriaastra.com" # update if needed
baseurl: "" # leave blank if site lives at root
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
plugins: []
